### ISSUE TITLE
Cut over to ScheduleOnce

### ISSUE THREAD

**Issue by raphaelcm** [bonusly/sales_playbook#1]
I've started using my ScheduleOnce calendar instead of YCBM, and it's working well: http://www.meetme.so/rcm_bonusly

@sahmehta3 can you update your demo calendar (http://www.meetme.so/sm_bonusly) and then reassign to me to create the master booking page for Bonusly Demos that includes both our calendars?

**Comment by sahmehta3** [comment]
The demo calendar is now linked to my account. I've updated the link in all templates that I send out.

@carltonbowers - can you start using ScheduleOnce to schedule demos for us?

**Comment by raphaelcm** [comment]
@carltonbowers You can use this page to access either of our calendars: http://www.meetme.so/bonusly_demo

**Comment by carltonbowers** [comment]
@raphaelcm Looks good, thanks guys
