### ISSUE TITLE
RFC: add fields to pipedrive to track other software used by leads?

### ISSUE THREAD

**Issue by raphaelcm** [bonusly/sales_playbook#2]
Could we add fields in pipedrive to track:

Social software? (Yammer, Chatter, Honey)
Chat software? (Slack, Hipchat, Flowdock, GChat, Lync/Skype 4 Biz, etc)
HRIS? (BambooHR, Workday, Namely, ADP, PeopleSoft, etc)
SSO? (Okta, OneLogin, Bitium, etc)
Project Mgmt? (Jira, Confluence, Trello, etc)
Google Apps? (y/n checkbox)

If we could do this, then we could start to accrue hard numbers on what software our leads are using and prioritize integrations accordingly.

 @sahmehta3 @carltonbowers thoughts?

**Comment by sahmehta3** [comment]
I agree, and have added the ones here that were not in before.

These can be tracked for each deal in the "Details" section on the left hand side. Just click "edit all" and add the details!
![screen shot 2015-11-16 at 2 11 52 pm](https://cloud.githubusercontent.com/assets/12619465/11191913/1670cc68-8c6c-11e5-909e-b081b98f5df6.png)

**Comment by raphaelcm** [comment]
Awesome, looks good. Closing.
